[package]
name = "gplda"
version = "0.0.1"
authors = [ "Alexander Terenin, Mans Magnusson, Kunal Sarkleh and collaborators" ]

[dependencies]
clap = "~2.19.0"
libc = "0.2.0"
rand = "0.3"
lazy_static = "0.2"
